### ISSUE TITLE
Hardware acceleration of cryptographic algorithms

### ISSUE THREAD

**Issue by 0xchaihu** [canopo/canokey-crypto#14]
Thanks for this great project and your effort! 
I have a question about the hardware acceleration. Looks like canokey project wraps mbedtls as the crypto algorithms layer. mbedtls mainstream doesn't include hardware acceleration implementation, so I think currently canokey project doesn't include the hardware acceleration or platform security features. Is my understanding correct? Thanks in advance.

**Comment by jiegec** [comment]
Canokey uses hardware acceleration on secure chip, but due to NDA reasons, the code cannot be open source. This repo contains a fallback implementation where hardware acceleration is unavailable.

**Comment by dangfan** [comment]
On platforms like STM32, if you would like to use X-CUBE-CRYPTOLIB, you can override the mbedtls by implementing the functions marked with __attribute__((weak)).

**Comment by 0xchaihu** [comment]
Hi @jiegec and @dangfan, thanks for your clear answer, after checking the x.com, I find you've already released a official version called CanoKey Pigeon, I guess this one uses the secure chip you mentioned, can the part number of the secure chip be disclosed?

**Comment by dangfan** [comment]
The chip that we use is HED CIU98320B.

**Comment by 0xchaihu** [comment]
Got it with many thanks.
